server:
  tomcat:
    connection-timeout: 5000
  port: 8080

spring:
  jpa:
    hibernate.ddl-auto: create-drop
    properties.hibernate:
      dialect: org.hibernate.dialect.MySQL5InnoDBDialect
      temp.use_jdbc_metadata_defaults: false
    show-sql: true

  datasource:
    initialization-mode: always
    url: jdbc:mysql://localhost:3306/camunda?autoReconnect=true
    username: root
    password: devdevdev

camunda.bpm.admin-user:
  id: demo
  password: demo

spring.jackson.serialization.FAIL_ON_EMPTY_BEANS: false

spring.mail:
  host: smtp.gmail.com
  port: 587
  username: upp2020tim29@gmail.com
  password: -

  properties.mail.smtp:
    auth: true
    connectiontimeout: 5000
    timeout: 5000
    writetimeout: 5000
    starttls.enable: true
